FROM node:18.8.0-alpine3.16 as BUILD
WORKDIR /app
COPY package.json /app/
RUN yarn
COPY . .
RUN yarn build
RUN yarn run export

FROM nginx:alpine-slim as RUNNER
COPY --from=BUILD /app/out /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf