FROM node:12.18.3-alpine as build
WORKDIR /app
COPY .env .
RUN source .env
ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/package.json /app
RUN yarn install
COPY frontend /app
RUN yarn run build
# stage 2 - build the final image and copy the react build files
FROM nginx:1.17.8-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]