FROM node:12.18.3-alpine as build
WORKDIR /app
COPY .env .
RUN source .env
ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/package.json /app
RUN npm install
COPY frontend /app
RUN npm build 
ENTRYPOINT [ "npm","start"]