version: '3.9'
services:
  app:
    build: 
      context: ./portafolio
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports: 
      - "3000:3000"
    volumes: 
      - ./portafolio/:/app/src/
      - /app/src/build
      - /app/node_modules
    restart: unless-stopped
  
    