FROM node:18.8.0-alpine3.16 as BUILD
ENV API_URL=https://api.chaoticteam.com
WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn
COPY . .
RUN yarn build
RUN yarn run export

FROM nginx:alpine-slim as RUNNER
COPY --from=BUILD /app/out /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf