version: '3.9'
services:
  app:
    container_name: portafolio
    image: "ghcr.io/al3xdiaz/portafolio:latest"
    depends_on:
      - strapi
  strapi:
    container_name: strapi
    image: "ghcr.io/al3xdiaz/strapi:latest"
