version: '3.9'
services:
  app:
    image: "ghcr.io/al3xdiaz/portafolio:latest"    
    ports: 
      - "3000:3000"
  strapi:
    image: "ghcr.io/al3xdiaz/strapi:latest"
    build: 
      context: ./strapi
      dockerfile: Dockerfile
    ports: 
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./strapi:/srv/app/