version: '3.4'
services:
 frontend:
    image: "ghcr.io/al3xdiaz/portafolio:latest"
    environment: 
        USERNAME: ${USERNAME}
    build:
        context: portafolio
        dockerfile: dockerfile${DOCKERFILE}
    ports: 
        - "3000:3000"    