version: '3.4'
services:
 frontend:
    environment: 
        CHOKIDAR_USEPOLLING: "true"
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: "frontend"
    image: "ghcr.io/al3xdiaz/portafolio:latest"
    ports: 
        - "8085:3000"
    restart: unless-stopped	