version: '3.9'
services:
 app:
    image: "ghcr.io/al3xdiaz/portafolio:latest"
    environment: 
        USERNAME: ${USERNAME:-al3xdiaz}
    build:
        context: portafolio
        dockerfile: ${DOCKERFILE:-dockerfile}
    ports: 
        - "3000:3000"