version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-dockerfile}
    environment:
      API_URL: $API_URL
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app/src/
      - /app/src/build
      - /app/node_modules
  
    