version: '3.9'
services:
  app:
    volumes: 
      - ./portafolio/:/app/src/
      - next_build:/app/src/build
    entrypoint: /app/src/entrypoint.sh yarn dev
    restart: unless-stopped
    build:
      context: portafolio
      dockerfile: ${DOCKERFILE:-dockerfile}
volumes:
  next_build: