version: '3.4'
services:
 frontend:
    container_name: "frontend"
    image: "docker.pkg.github.com/al3xdiaz/portafolio/frontend:latest"
    ports: 
        - "80:80"
    depends_on: 
        - "backend"
 backend:
    env_file: 
        - ".env"
    container_name: "backend"
    image: "docker.pkg.github.com/al3xdiaz/portafolio/backend:latest"
    depends_on: 
        - "db"
 db:
    container_name: db
    image: mongo
    #restart: always
    volumes: 
        - ./mongo/data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_U}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_P}
