version: '3.4'
services:
 frontend:
    environment: 
        CHOKIDAR_USEPOLLING: "true"
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: "frontend"
    build:
        context: frontend/
        dockerfile: dockerfile.test
    ports: 
        - "3000:3000"
    #restart: always
    volumes: 
        - "./frontend/src:/code/src"
        - "./frontend/public:/code/public"