version: '3.4'
services:
 frontend:
    environment: 
        CHOKIDAR_USEPOLLING: "true"
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: "frontend"
    image: "docker.pkg.github.com/al3xdiaz/portafolio/frontend:latest"
    build:
        context: .
        dockerfile: frontend/dockerfile.prod
#        dockerfile: frontend/dockerfile.prod
    ports: 
        - "8085:3000"
    #restart: always
    volumes: 
        - "./frontend/src:/code/src"
        - "./frontend/public:/code/public"