version: '3.9'
services:
  app:
    container_name: portafolio
    image: "ghcr.io/al3xdiaz/portafolio:latest"
    ports: 
      - "3000:3000"
    environment:
      API_URL: ${API_URL:-http://localhost:1337}
    depends_on:
      - strapi
  strapi:
    container_name: strapi
    image: "ghcr.io/al3xdiaz/strapi:latest"
    ports: 
      - "1337:1337"
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}