FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV="development"
ENV FLASK_APP=main.py

RUN apk add --no-cache gcc musl-dev linux-headers
COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["flask", "run"]