---
- hosts: all
  become: "no"
  tasks:
    - ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/apps"
        state: directory
      name: create apps directory
    - ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/apps/portafolio"
        state: directory
      name: create workspace directory
    - ansible.builtin.copy:
        dest: "{{ ansible_facts['user_dir'] }}/apps/portafolio"
        content: |
          version: '3.9'
          services:
            portafolio:
              image: ghcr.io/al3xdiaz/portafolio:latest
              ports:
                - "8000:3000"
    - ansible.builtin.docker_compose:
        project_src: "{{ ansible_facts['user_dir'] }}/apps/portafolio"
        project_name: portafolio
        state: present
    - name: config nginx
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/portafolio
        content: |
          server {
            listen 80;
            server_name alexdiaz.chaoticteam.com;
            location / {
              proxy_pass http://localhost:8000;
            }
          }
    - name: enable nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/portafolio
        dest: /etc/nginx/sites-enabled/portafolio
        state: link
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: "yes"
...