---
- hosts: all
  become: "no"
  tasks:
    - ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/apps"
        state: directory
      name: create apps directory
    - ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/apps/portafolio"
        state: directory
      name: create workspace directory
    - ansible.builtin.copy:
        content: |
          version: '3.9'
          services:
            portafolio:
              image: ghcr.io/al3xdiaz/portafolio:{{ version | default('latest') }}
              ports:
                - "8000:3000"
        dest: "{{ ansible_facts['user_dir'] }}/apps/portafolio/docker-compose.yml"
    - name: Clean up Docker images
      docker_prune:
        images: yes
        images_filters:
          dangling: false
    - ansible.builtin.docker_compose:
        project_src: "{{ ansible_facts['user_dir'] }}/apps/portafolio"
        project_name: portafolio
        state: present
