name: CI portafolio

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - '**'

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: portafolio
  WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
  WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      image_id: ${{ steps.set_tags.outputs.image_id }}
      git_tag_latest: ${{ steps.set_tags.outputs.git_tag_latest }}
      docker_tag: ${{ steps.set_tags.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Tags
        id: set_tags
        run: |
          echo "Building image..."
          echo REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" > .env 
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          echo "Change all uppercase to lowercase"
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo "get information about the git: ${{ github.ref_name }}"
          GIT_BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '[A-Z]' '[a-z]')
          GIT_TAG_LATEST=$(echo ${{ github.github_ref }} | tr '[A-Z]' '[a-z]')
          # GIT_TAG_LATEST=$(echo $(git describe --tags --abbrev=0) | tr '[A-Z]' '[a-z]')
          echo "git tag latest: $GIT_TAG_LATEST"

          DOCKER_TAG="latest"
          [[ $GIT_BRANCH_NAME == "main" ]] && DOCKER_TAG="stable"
          echo "set docker tag: $DOCKER_TAG"

          echo "::set-output name=image_id::$IMAGE_ID"
          echo "::set-output name=git_tag_latest::$GIT_TAG_LATEST"
          echo "::set-output name=docker_tag::$DOCKER_TAG"

      - name: Build image tag
        if: github.ref_type == 'tag'
        run: |
          echo "build image"
          TAG=${{needs.build-push.outputs.image_id}}:${{needs.build-push.outputs.git_tag_latest}}
          docker build portafolio --file portafolio/dockerfile.prod --tag $TAG--label "runnumber=${GITHUB_RUN_ID}"
      - name: Build image latest
        run: |
          TAG=${{needs.build-push.outputs.image_id}}:${{needs.build-push.outputs.docker_tag}}
          echo "build image"
          docker build portafolio --file portafolio/dockerfile.prod --tag $TAG --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.CICD_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name:  Push image
        run: |
            # docker push -a $(docker images | grep "$IMAGE_NAME" | awk '{print $1}' | awk 'NR==1')
            IMAGE_ID=${{needs.build-push.outputs.image_id}}
            DOCKER_TAG=${{needs.build-push.outputs.docker_tag}}
            GIT_TAG_LATEST=${{needs.build-push.outputs.git_tag_latest}}
            docker push $IMAGE_ID:$DOCKER_TAG
            docker push $IMAGE_ID:$GIT_TAG_LATEST