name: CI portafolio

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - '**'

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: portafolio
  WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
  WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run:  |
                # echo REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" > .env  
                IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
                # Change all uppercase to lowercase
                IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

                GIT_BRANCH_NAME=`git branch | grep "*" | cut -d " " -f 2`
                GIT_TAG=`git describe --tags --abbrev=0` 

                [[ $GIT_BRANCH_NAME == "main" ]] && DOCKER_TAG="stable" || DOCKER_TAG="latest"

                docker build . --file portafolio/dockerfile.prod --tag $IMAGE_ID:$DOCKER_TAG --tag $IMAGE_ID:GIT_TAG --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.CICD_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name:  Push image
        run: |
            docker push -a $(docker images | grep "$IMAGE_NAME" | awk '{print $1}' | awk 'NR==1')
      # - name: The job has succeeded
      #   if: ${{ success() }}
      #   run: source webhook.sh true
      # - name: The job has failure
      #   if: ${{ failure() }}
      #   run: source webhook.sh false