name: CI portafolio

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - '**'

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  WEBHOOK_ID: "${{ secrets.WEBHOOK_ID }}"
  WEBHOOK_TOKEN: "${{ secrets.WEBHOOK_TOKEN }}"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: gitversion
        uses: gittools/actions/gitversion/execute@v0
        id: gitversion
        with:
          useConfigFile: true

      - uses: actions/checkout@v2
      - name: Set Tags
        id: build
        run: |
          echo "Building image..."
          echo "Change all uppercase to lowercase"
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          TAG="${{ steps.gitversion.outputs.MajorMinorPatch }}"
          LONG_TAG="${{ steps.gitversion.outputs.FullSemVer }}"
          echo "::set-output name=docker_tag::$DOCKER_TAG"
          echo "::set-output name=docker_tag_long::$LONG_TAG"

      - name: Build portafolio
        if: github.ref_type == 'tag'
        run: |
          echo "build image"
          docker build portafolio --file portafolio/Dockerfile.prod --tag $REGISTRY/portafolio:latest
      - name: Build strapi
        run: |
          echo "build image"
          docker build strapi --file strapi/Dockerfile.prod --tag $REGISTRY/strapi:latest

      - name: tag docker images
        run: |
          TAG=${{ steps.build.outputs.docker_tag }}
          TAG_LONG=${{ steps.build.outputs.docker_tag_long }}
          docker tag $REGISTRY/portafolio:latest $REGISTRY/portafolio:$TAG
          docker tag $REGISTRY/strapi:latest $REGISTRY/strapi:$TAG
          docker tag $REGISTRY/portafolio:latest $REGISTRY/portafolio:$TAG_LONG
          docker tag $REGISTRY/strapi:latest $REGISTRY/strapi:$TAG_LONG

      - name: Log in to registry # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.CICD_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Push tag image to registry
        if: github.ref_type == 'tag'
        run: |
          docker push $IMAGE_ID:${{ steps.build.outputs.docker_tag }}
          docker push $IMAGE_ID:${{ steps.build.outputs.docker_tag_long }}
          # if branch is master, push image with `latest` tag
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker push $IMAGE_ID:latest
          fi
      - name: success
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
      - name: fail
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} pipeline failure.'